project:
  type: website
  output-dir: docs
website:
  title: "Hongke (Amy) Wu"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Profile
      - Publications.qmd
      - Volunteer.qmd
format:
  html:
    theme: minty
    css: styles.css
    toc: true



