project:
  type: website
  output-dir: docs
website:
  title: "Hongke (Amy) Wu"
  navbar:
    left:
      - href: index.qmd
        text: Profile
      - href: Publications.qmd
        text: Publications
      - href: Volunteer.qmd
        text: Volunteer
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



